[pytest]
; This is a configuration file for pytest.
markers =
    e2e: marks tests as end-to-end tests

; --- Logging Configuration ---
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s - %(levelname)s - %(name)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
